FROM java:8
LABEL maintainer=“gabrielviviani98@hotmail.com”
VOLUME /tmp
EXPOSE 8080
ADD target/xy-inc-0.0.1-SNAPSHOT.jar xy-inc-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","xy-inc-0.0.1-SNAPSHOT.jar"]

